### ISSUE TITLE
Docker image 

### ISSUE THREAD

**Issue by ronhks** [cvitter/mattermost-bitbucket-bridge#3]
Hello!

Can you compose a docker image of this extension? :)

**Comment by cvitter** [comment]
Hi @ronhks, I would love to but I am not sure when I will have the time to get around to doing it. I will tag this request and see if someone can get to it before I do!

**Comment by ronhks** [comment]
Hi @cvitter, 

If I have time, I would help you in it, but in python I'm not experienced :/ so if i got a wall, may i ask you?

**Comment by cvitter** [comment]
Absolutely!

**Comment by ronhks** [comment]
I made a first version of it.

https://github.com/ronhks/mattermost-bitbucket-bridge/tree/docker-image-making

Please check it, if you have time.

I need your help to start the python script, because I can't start it my own :/

**Comment by cvitter** [comment]
The docker file looks right to me although I haven't had a chance to test it. You do need to add the command in `docker run` to open the ports you need to access that running Flask application. Should look something like `docker run -d -p 5006:5006 cvitter-mattermost-bitbucket-bridge` (although I tend to use Docker Compose like: https://github.com/cvitter/jenkins-demo-environment so my `docker run` is rusty.)

**Comment by ronhks** [comment]
good. 

I run into some python missing packages problem.

Right now, I got this error:

```Traceback (most recent call last):
  File "./bitbucket.py", line 5, in <module>
    import helpers
ModuleNotFoundError: No module named 'helpers'
```
I tried to fix it (the commented line in the fresh Dockerfile, but it doesn't works :/

`Dockerfile`:
https://github.com/ronhks/mattermost-bitbucket-bridge/blob/docker-image-making/Dockerfile

**Comment by cvitter** [comment]
Sorry I missed that, you need to add the helpers.py file to your docker file. I submitted a PR for that.

**Comment by ronhks** [comment]
It seems, it works for me :)

So I made a pull request :)

**Comment by cvitter** [comment]
Thanks @ronhks for all of your help on this! Great work.

**Comment by cvitter** [comment]
@ronhks the master branch has been updated with your code.
